"""add_associate_memory

Revision ID: bced87540914
Revises: 3a6633832562
Create Date: 2026-03-17 16:42:47.429388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bced87540914'
down_revision: Union[str, None] = '3a6633832562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_firm_profiles_user_id'), 'firm_profiles', ['user_id'], unique=False)
    op.alter_column('startups', 'sources_visited',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('startups', 'sources_visited',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_firm_profiles_user_id'), table_name='firm_profiles')
    # ### end Alembic commands ###
