import asyncio
import re
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.core.database import AsyncSessionLocal
from app.models.company import Company
from app.models.firm_company_score import FirmCompanyScore
from app.models.firm_profile import FirmProfile

def slugify(name: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

FIRM_PROFILE = {
    "firm_name": "Failup Ventures",
    "investment_stages": ["pre-seed", "seed", "Series A"],
    "geography_focus": ["North America", "Europe"],
    "check_size_min": 250000,
    "check_size_max": 2000000,
    "investment_thesis": "We invest in AI-native B2B SaaS companies automating knowledge work in regulated verticals including legal, finance, healthcare, and compliance. We look for founders using AI to replace entire workflows, not just assist humans.",
    "excluded_sectors": ["crypto", "gambling", "defense", "hardware"],
    "fit_threshold": 3,
    "is_active": True
}

STARTUPS = [
    # Top Matches (fit_score 5)
    {"name": "Lexi AI", "one_liner": "AI-native legal research platform that automates case analysis for law firms", "sector": "Legal Tech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 3200000, "top_investors": ["Bessemer", "Y Combinator"], "thesis_tags": ["AI-native", "B2B SaaS", "legal", "workflow automation"], "business_model": "SaaS", "target_customer": "Mid-size law firms", "source": "YC", "fit_reasoning": "Exactly the thesis — AI-native, B2B, legal vertical, replacing entire research workflows not just assisting.", "recommended_next_step": "Request intro via Bessemer network. High conviction."},
    {"name": "ComplianceOS", "one_liner": "Automated compliance monitoring and reporting for financial institutions", "sector": "FinTech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 4100000, "top_investors": ["a16z", "Sequoia Scout"], "thesis_tags": ["AI-native", "compliance", "finance", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Regional banks and credit unions", "source": "TechCrunch", "fit_reasoning": "Strong fit — regulated vertical (finance), AI-native compliance automation, B2B SaaS model.", "recommended_next_step": "Reach out directly to founder. Seed stage aligns with check size."},
    {"name": "MedScribe AI", "one_liner": "Ambient AI clinical documentation that writes notes while doctors see patients", "sector": "HealthTech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 5500000, "top_investors": ["General Catalyst", "Andreessen Horowitz"], "thesis_tags": ["AI-native", "healthcare", "workflow automation", "B2B SaaS"], "business_model": "Per-seat SaaS", "target_customer": "Outpatient clinics and hospital systems", "source": "ProductHunt", "fit_reasoning": "Top match — healthcare regulated vertical, ambient AI replacing full documentation workflow.", "recommended_next_step": "Monitor — slightly above typical check size but worth tracking for follow-on."},
    {"name": "AuditMind", "one_liner": "AI that automates financial audit workpapers and flags anomalies in real time", "sector": "FinTech", "funding_stage": "pre-seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 800000, "top_investors": ["Village Global"], "thesis_tags": ["AI-native", "audit", "finance", "automation"], "business_model": "SaaS", "target_customer": "Accounting firms and internal audit teams", "source": "YC", "fit_reasoning": "Perfect fit — pre-seed, regulated vertical, AI automating knowledge work entirely.", "recommended_next_step": "Move to outreach immediately. Pre-seed check size aligns perfectly."},
    {"name": "Paralegal AI", "one_liner": "End-to-end contract review and negotiation automation for in-house legal teams", "sector": "Legal Tech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 6000000, "top_investors": ["Founders Fund", "Kleiner Perkins"], "thesis_tags": ["AI-native", "legal", "contract automation", "B2B"], "business_model": "Usage-based SaaS", "target_customer": "In-house legal at Fortune 500", "source": "Crunchbase", "fit_reasoning": "Strong thesis match — legal vertical, AI replacing paralegal workflow, B2B enterprise.", "recommended_next_step": "Request intro via Kleiner network."},
    {"name": "ReguBot", "one_liner": "AI regulatory change monitoring and impact analysis for compliance teams", "sector": "RegTech", "funding_stage": "pre-seed", "ai_score": 4, "fit_score": 5, "funding_amount_usd": 600000, "top_investors": ["Precursor Ventures"], "thesis_tags": ["regulatory", "compliance", "AI-native", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Compliance officers at banks", "source": "StrictlyVC", "fit_reasoning": "Excellent fit — RegTech is squarely in the mandate, pre-seed stage, AI-native approach.", "recommended_next_step": "Schedule intro call. Strong mandate alignment."},
    {"name": "ClaimFlow", "one_liner": "AI-powered insurance claims processing that reduces settlement time by 70%", "sector": "InsurTech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 4800000, "top_investors": ["Inspired Capital", "Anthemis"], "thesis_tags": ["AI-native", "insurance", "workflow automation", "regulated vertical"], "business_model": "Per-claim SaaS", "target_customer": "P&C insurance carriers", "source": "VentureBeat", "fit_reasoning": "Strong fit — regulated vertical (insurance), AI automating claims workflow end to end.", "recommended_next_step": "Reach out to founder directly via LinkedIn."},
    {"name": "TaxPilot", "one_liner": "Autonomous tax preparation and filing platform for SMBs powered by LLMs", "sector": "FinTech", "funding_stage": "pre-seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 1200000, "top_investors": ["500 Startups"], "thesis_tags": ["AI-native", "tax", "finance", "workflow automation"], "business_model": "SaaS + transaction fee", "target_customer": "Small business owners", "source": "ProductHunt", "fit_reasoning": "Top match — autonomous AI replacing tax workflow, finance vertical, pre-seed check size.", "recommended_next_step": "Move to outreach. High conviction pre-seed opportunity."},

    # Strong Fits (fit_score 4)
    {"name": "Draftwise", "one_liner": "AI contract drafting assistant trained on legal precedents for transactional lawyers", "sector": "Legal Tech", "funding_stage": "Series A", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 12000000, "top_investors": ["Tiger Global"], "thesis_tags": ["AI", "legal", "drafting", "B2B"], "business_model": "SaaS", "target_customer": "BigLaw associates", "source": "Crunchbase", "fit_reasoning": "Strong fit on vertical and AI-nativeness. Series A is at the edge of check size range.", "recommended_next_step": "Monitor for 30 days. May be too far along for initial check."},
    {"name": "Nym Health", "one_liner": "Autonomous medical coding platform using NLP to replace manual billing workflows", "sector": "HealthTech", "funding_stage": "Series A", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 25000000, "top_investors": ["Optum Ventures"], "thesis_tags": ["AI", "healthcare", "revenue cycle", "automation"], "business_model": "Per-claim SaaS", "target_customer": "Hospital revenue cycle teams", "source": "TechCrunch", "fit_reasoning": "Healthcare regulated vertical, strong AI workflow automation. Above typical check size.", "recommended_next_step": "Track for Series B signal. Too large for current check range."},
    {"name": "Nira", "one_liner": "AI-powered document access control and compliance for Google Workspace", "sector": "Cybersecurity", "funding_stage": "seed", "ai_score": 3, "fit_score": 4, "funding_amount_usd": 7000000, "top_investors": ["General Catalyst"], "thesis_tags": ["compliance", "security", "SaaS", "B2B"], "business_model": "SaaS", "target_customer": "IT and security teams", "source": "TechCrunch", "fit_reasoning": "Good fit — compliance focus, B2B SaaS, though security isn't the core thesis vertical.", "recommended_next_step": "Request more info on AI roadmap before committing."},
    {"name": "Instabase", "one_liner": "AI platform for automating document-heavy business processes in regulated industries", "sector": "Enterprise AI", "funding_stage": "Series B", "ai_score": 5, "fit_score": 4, "funding_amount_usd": 105000000, "top_investors": ["Greylock", "Andreessen Horowitz"], "thesis_tags": ["AI-native", "document automation", "regulated vertical", "B2B"], "business_model": "Enterprise SaaS", "target_customer": "Banks, insurers, government agencies", "source": "Crunchbase", "fit_reasoning": "Thesis aligned but too late stage for current fund size.", "recommended_next_step": "Pass on investment. Monitor as competitive signal."},
    {"name": "Filevine", "one_liner": "AI-enhanced legal case management and document automation for law firms", "sector": "Legal Tech", "funding_stage": "Series C", "ai_score": 3, "fit_score": 4, "funding_amount_usd": 108000000, "top_investors": ["Golub Capital"], "thesis_tags": ["legal", "case management", "SaaS", "automation"], "business_model": "SaaS", "target_customer": "Personal injury and litigation firms", "source": "Crunchbase", "fit_reasoning": "Good vertical fit but well beyond early-stage scope.", "recommended_next_step": "Pass — too late stage."},
    {"name": "Waymark", "one_liner": "AI video creation platform for local business advertising at scale", "sector": "MarTech", "funding_stage": "Series A", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 12400000, "top_investors": ["Spark Capital"], "thesis_tags": ["AI", "video", "SMB", "automation"], "business_model": "SaaS", "target_customer": "Local businesses and agencies", "source": "TechCrunch", "fit_reasoning": "AI-native product but marketing tech is outside the regulated vertical focus.", "recommended_next_step": "Pass on current thesis. Revisit if thesis expands."},
    {"name": "Hebbia", "one_liner": "AI research platform for analysts at investment banks and law firms", "sector": "Enterprise AI", "funding_stage": "Series A", "ai_score": 5, "fit_score": 4, "funding_amount_usd": 30000000, "top_investors": ["Peter Thiel", "Index Ventures"], "thesis_tags": ["AI-native", "research automation", "finance", "legal"], "business_model": "Enterprise SaaS", "target_customer": "Investment banks and law firms", "source": "StrictlyVC", "fit_reasoning": "Strong thesis alignment — finance and legal verticals, AI automating research workflows.", "recommended_next_step": "Explore co-investment angle. Strong product conviction."},
    {"name": "EvenUp", "one_liner": "AI that writes demand letters for personal injury lawyers automatically", "sector": "Legal Tech", "funding_stage": "Series B", "ai_score": 5, "fit_score": 4, "funding_amount_usd": 65000000, "top_investors": ["Base10", "Bessemer"], "thesis_tags": ["AI-native", "legal", "document automation", "B2B"], "business_model": "Per-document SaaS", "target_customer": "Personal injury law firms", "source": "TechCrunch", "fit_reasoning": "Perfect vertical and AI-nativeness but too late stage for fund size.", "recommended_next_step": "Pass on check size grounds. Strong signal for legal AI thesis."},
    {"name": "Turion", "one_liner": "AI-powered underwriting automation for specialty insurance carriers", "sector": "InsurTech", "funding_stage": "seed", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 5500000, "top_investors": ["Valor Equity"], "thesis_tags": ["insurance", "underwriting", "AI automation", "B2B"], "business_model": "SaaS", "target_customer": "Specialty insurance carriers", "source": "VentureBeat", "fit_reasoning": "Regulated vertical, seed stage, AI automating underwriting workflow.", "recommended_next_step": "Add to watchlist. Request metrics call."},

    # Possible Fits (fit_score 3)
    {"name": "Cohere", "one_liner": "Enterprise AI platform providing NLP APIs for business applications", "sector": "AI Infrastructure", "funding_stage": "Series C", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 445000000, "top_investors": ["Tiger Global", "Nvidia"], "thesis_tags": ["AI", "NLP", "enterprise", "infrastructure"], "business_model": "API usage", "target_customer": "Enterprise developers", "source": "TechCrunch", "fit_reasoning": "Highly AI-native but infrastructure layer, not workflow automation. Too late stage.", "recommended_next_step": "Pass — infrastructure play, not mandate aligned."},
    {"name": "Harvey AI", "one_liner": "Generative AI for legal professionals built on GPT-4", "sector": "Legal Tech", "funding_stage": "Series B", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 100000000, "top_investors": ["Sequoia", "OpenAI Fund"], "thesis_tags": ["AI", "legal", "generative AI", "B2B"], "business_model": "Enterprise SaaS", "target_customer": "BigLaw firms", "source": "TechCrunch", "fit_reasoning": "Perfect vertical but too late stage and too large.", "recommended_next_step": "Pass. Monitor as market signal for legal AI."},
    {"name": "Abridge", "one_liner": "AI medical conversation platform that summarizes patient-doctor interactions", "sector": "HealthTech", "funding_stage": "Series B", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 150000000, "top_investors": ["Spark Capital", "UPMC Enterprises"], "thesis_tags": ["AI", "healthcare", "documentation", "ambient"], "business_model": "Enterprise SaaS", "target_customer": "Health systems", "source": "TechCrunch", "fit_reasoning": "Thesis aligned healthcare AI but well beyond early-stage.", "recommended_next_step": "Pass on stage. Strong competitive signal."},
    {"name": "Superhuman", "one_liner": "AI-powered email client that makes professionals twice as fast", "sector": "Productivity", "funding_stage": "Series B", "ai_score": 3, "fit_score": 3, "funding_amount_usd": 75000000, "top_investors": ["First Round", "IVP"], "thesis_tags": ["AI", "productivity", "SaaS", "B2B"], "business_model": "SaaS", "target_customer": "Knowledge workers", "source": "ProductHunt", "fit_reasoning": "AI-assisted not AI-native. Not a regulated vertical. More consumer than enterprise.", "recommended_next_step": "Pass on thesis grounds."},
    {"name": "Tome", "one_liner": "AI presentation and storytelling tool for business professionals", "sector": "Productivity", "funding_stage": "Series B", "ai_score": 3, "fit_score": 2, "funding_amount_usd": 75000000, "top_investors": ["Lightspeed", "Greylock"], "thesis_tags": ["AI", "productivity", "presentations"], "business_model": "Freemium SaaS", "target_customer": "Sales and marketing teams", "source": "ProductHunt", "fit_reasoning": "Not regulated vertical. AI-assisted tool, not workflow replacement.", "recommended_next_step": "Pass."},
    {"name": "Glean", "one_liner": "AI-powered workplace search connecting all company knowledge and apps", "sector": "Enterprise AI", "funding_stage": "Series D", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 260000000, "top_investors": ["Sequoia", "Kleiner Perkins"], "thesis_tags": ["AI", "enterprise search", "knowledge management", "B2B"], "business_model": "Enterprise SaaS", "target_customer": "Enterprise IT teams", "source": "TechCrunch", "fit_reasoning": "Strong AI product but enterprise search is adjacent to core thesis. Too late stage.", "recommended_next_step": "Pass."},
    {"name": "Writer", "one_liner": "Full-stack generative AI platform for enterprise content and workflows", "sector": "Enterprise AI", "funding_stage": "Series C", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 200000000, "top_investors": ["Iconiq Growth", "Balderton"], "thesis_tags": ["AI", "enterprise", "content automation", "B2B SaaS"], "business_model": "Enterprise SaaS", "target_customer": "Enterprise marketing and ops teams", "source": "VentureBeat", "fit_reasoning": "AI-native platform but content/marketing focus, not regulated vertical. Too late stage.", "recommended_next_step": "Pass on current thesis."},
    {"name": "Moveworks", "one_liner": "AI platform for enterprise IT and HR support ticket automation", "sector": "Enterprise AI", "funding_stage": "Series C", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 305000000, "top_investors": ["Tiger Global", "Kleiner Perkins"], "thesis_tags": ["AI", "enterprise", "IT automation", "workflow"], "business_model": "Enterprise SaaS", "target_customer": "Enterprise IT departments", "source": "TechCrunch", "fit_reasoning": "Workflow automation but IT/HR focus is outside regulated verticals mandate.", "recommended_next_step": "Pass."},
    {"name": "Ironclad", "one_liner": "Digital contracting platform for legal and procurement teams", "sector": "Legal Tech", "funding_stage": "Series D", "ai_score": 3, "fit_score": 3, "funding_amount_usd": 333000000, "top_investors": ["Y Combinator", "Accel"], "thesis_tags": ["legal", "contracts", "workflow", "B2B SaaS"], "business_model": "Enterprise SaaS", "target_customer": "Legal operations teams", "source": "Crunchbase", "fit_reasoning": "Legal vertical but CLM category, not AI-native. Too late stage.", "recommended_next_step": "Pass."},

    # Additional companies for volume
    {"name": "Docugami", "one_liner": "AI that reads, writes and analyzes business documents to automate workflows", "sector": "Enterprise AI", "funding_stage": "Series A", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 10000000, "top_investors": ["Madrona Venture Group"], "thesis_tags": ["AI-native", "document automation", "B2B", "regulated"], "business_model": "SaaS", "target_customer": "Financial services and legal teams", "source": "TechCrunch", "fit_reasoning": "Strong fit — document AI for regulated verticals, Series A stage.", "recommended_next_step": "Schedule call with founder."},
    {"name": "Sana Labs", "one_liner": "AI learning platform that personalizes corporate training and knowledge management", "sector": "HR Tech", "funding_stage": "Series B", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 34000000, "top_investors": ["EQT Ventures"], "thesis_tags": ["AI", "learning", "enterprise", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Enterprise L&D teams", "source": "VentureBeat", "fit_reasoning": "AI-native but HR/learning is outside regulated vertical focus.", "recommended_next_step": "Pass on thesis grounds."},
    {"name": "Otter.ai", "one_liner": "AI meeting transcription and collaboration tool for teams", "sector": "Productivity", "funding_stage": "Series B", "ai_score": 3, "fit_score": 2, "funding_amount_usd": 20000000, "top_investors": ["Georgian"], "thesis_tags": ["AI", "transcription", "productivity", "SaaS"], "business_model": "Freemium SaaS", "target_customer": "Business professionals", "source": "ProductHunt", "fit_reasoning": "Not regulated vertical. AI-assisted, not AI-native replacement.", "recommended_next_step": "Pass."},
    {"name": "Gradient AI", "one_liner": "AI underwriting and claims management platform for the insurance industry", "sector": "InsurTech", "funding_stage": "Series B", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 56000000, "top_investors": ["Volition Capital", "MassMutual Ventures"], "thesis_tags": ["AI", "insurance", "underwriting", "regulated vertical"], "business_model": "SaaS", "target_customer": "Insurance carriers", "source": "VentureBeat", "fit_reasoning": "Regulated vertical, AI automation of core insurance workflows. Late stage.", "recommended_next_step": "Monitor as competitive signal in InsurTech."},
    {"name": "Cogna", "one_liner": "AI-native compliance and risk management platform for healthcare providers", "sector": "HealthTech", "funding_stage": "pre-seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 500000, "top_investors": ["Hustle Fund"], "thesis_tags": ["AI-native", "healthcare", "compliance", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Hospital compliance departments", "source": "StrictlyVC", "fit_reasoning": "Exact thesis match — AI-native, healthcare, compliance, pre-seed stage.", "recommended_next_step": "Immediate outreach. Pre-seed check size, perfect mandate fit."},
    {"name": "Anterior", "one_liner": "AI clinical decision support automating prior authorization for health plans", "sector": "HealthTech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 3500000, "top_investors": ["General Catalyst", "Y Combinator"], "thesis_tags": ["AI-native", "healthcare", "prior auth", "workflow automation"], "business_model": "SaaS", "target_customer": "Health plans and payers", "source": "YC", "fit_reasoning": "Outstanding fit — healthcare regulated vertical, AI replacing prior auth workflow entirely.", "recommended_next_step": "Request intro via GC network immediately."},
    {"name": "Eleos Health", "one_liner": "AI ambient platform for behavioral health documentation and insights", "sector": "HealthTech", "funding_stage": "Series A", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 20000000, "top_investors": ["Andreessen Horowitz"], "thesis_tags": ["AI", "behavioral health", "documentation", "regulated"], "business_model": "Per-provider SaaS", "target_customer": "Behavioral health providers", "source": "TechCrunch", "fit_reasoning": "Healthcare regulated, AI documentation automation. Series A edge of range.", "recommended_next_step": "Watch for Series A close details."},
    {"name": "Vial", "one_liner": "AI-powered clinical trial management platform for biotech sponsors", "sector": "HealthTech", "funding_stage": "Series B", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 68000000, "top_investors": ["a16z Bio", "General Catalyst"], "thesis_tags": ["AI", "clinical trials", "healthcare", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Biotech and pharma companies", "source": "TechCrunch", "fit_reasoning": "Healthcare but clinical trial ops is niche. Too late stage.", "recommended_next_step": "Pass on stage."},
    {"name": "Aeye Health", "one_liner": "AI diagnostic platform automating eye disease detection from retinal images", "sector": "HealthTech", "funding_stage": "Series A", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 18000000, "top_investors": ["Optum Ventures"], "thesis_tags": ["AI", "diagnostics", "healthcare", "imaging"], "business_model": "Per-scan SaaS", "target_customer": "Ophthalmology clinics", "source": "VentureBeat", "fit_reasoning": "Healthcare AI but diagnostics/imaging is outside core knowledge work automation focus.", "recommended_next_step": "Pass on thesis fit."},
    {"name": "Priceva", "one_liner": "AI pricing intelligence and dynamic pricing automation for e-commerce", "sector": "E-commerce", "funding_stage": "seed", "ai_score": 3, "fit_score": 2, "funding_amount_usd": 2000000, "top_investors": ["Launch Capital"], "thesis_tags": ["AI", "pricing", "e-commerce", "automation"], "business_model": "SaaS", "target_customer": "Online retailers", "source": "ProductHunt", "fit_reasoning": "Not regulated vertical. E-commerce pricing outside mandate.", "recommended_next_step": "Pass."},
    {"name": "Lilt", "one_liner": "AI translation and localization platform for enterprise content", "sector": "Enterprise AI", "funding_stage": "Series C", "ai_score": 3, "fit_score": 2, "funding_amount_usd": 55000000, "top_investors": ["Sequoia"], "thesis_tags": ["AI", "translation", "enterprise", "localization"], "business_model": "Enterprise SaaS", "target_customer": "Global enterprises", "source": "TechCrunch", "fit_reasoning": "Not regulated vertical. Translation is adjacent, not core.", "recommended_next_step": "Pass."},
    {"name": "Truework", "one_liner": "AI-powered income and employment verification platform for lenders", "sector": "FinTech", "funding_stage": "Series C", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 50000000, "top_investors": ["Sequoia", "Khosla Ventures"], "thesis_tags": ["AI", "verification", "finance", "regulated vertical"], "business_model": "Per-verification SaaS", "target_customer": "Mortgage lenders and banks", "source": "TechCrunch", "fit_reasoning": "Finance regulated vertical, AI automating verification workflows. Late stage for fund.", "recommended_next_step": "Monitor as competitive signal."},
    {"name": "Sightline", "one_liner": "AI contract intelligence for real estate investment and asset management firms", "sector": "PropTech", "funding_stage": "seed", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 3800000, "top_investors": ["Fifth Wall"], "thesis_tags": ["AI", "contracts", "real estate", "regulated"], "business_model": "SaaS", "target_customer": "Real estate investment firms", "source": "StrictlyVC", "fit_reasoning": "Regulated-adjacent vertical, AI contract automation, seed stage fits check range.", "recommended_next_step": "Schedule call. Adjacent to core thesis."},
    {"name": "Legalon", "one_liner": "AI contract analysis and risk scoring platform for enterprise legal teams", "sector": "Legal Tech", "funding_stage": "pre-seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 750000, "top_investors": ["Operator Collective"], "thesis_tags": ["AI-native", "legal", "contract analysis", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Enterprise legal departments", "source": "ProductHunt", "fit_reasoning": "Exact fit — legal vertical, AI-native, pre-seed, contract workflow automation.", "recommended_next_step": "High priority outreach. Perfect mandate match."},
    {"name": "Vanta", "one_liner": "Automated security compliance platform for SOC 2 and ISO 27001 certification", "sector": "Cybersecurity", "funding_stage": "Series C", "ai_score": 3, "fit_score": 3, "funding_amount_usd": 110000000, "top_investors": ["Sequoia", "Y Combinator"], "thesis_tags": ["compliance", "security", "automation", "B2B SaaS"], "business_model": "SaaS", "target_customer": "Tech startups and SMBs", "source": "TechCrunch", "fit_reasoning": "Compliance automation but security-focused, not knowledge work in regulated industry. Too late stage.", "recommended_next_step": "Pass."},
    {"name": "Eigen Technologies", "one_liner": "AI document processing platform for financial services and insurance", "sector": "FinTech", "funding_stage": "Series B", "ai_score": 5, "fit_score": 4, "funding_amount_usd": 37000000, "top_investors": ["Goldman Sachs", "Temasek"], "thesis_tags": ["AI-native", "document processing", "finance", "regulated vertical"], "business_model": "Enterprise SaaS", "target_customer": "Investment banks and insurers", "source": "TechCrunch", "fit_reasoning": "Excellent thesis fit — finance regulated vertical, AI document automation. Slightly late stage.", "recommended_next_step": "Explore secondary opportunity or Series C follow."},
    {"name": "Clerky", "one_liner": "Automated legal document generation platform for startup formation", "sector": "Legal Tech", "funding_stage": "Series A", "ai_score": 2, "fit_score": 3, "funding_amount_usd": 8000000, "top_investors": ["Y Combinator"], "thesis_tags": ["legal", "automation", "SaaS", "B2B"], "business_model": "Transaction-based SaaS", "target_customer": "Early-stage startups", "source": "Crunchbase", "fit_reasoning": "Legal vertical but not AI-native. Document automation via templates, not AI reasoning.", "recommended_next_step": "Pass — not sufficiently AI-native."},
    {"name": "Norm AI", "one_liner": "AI regulatory compliance automation for financial services using symbolic AI", "sector": "RegTech", "funding_stage": "seed", "ai_score": 5, "fit_score": 5, "funding_amount_usd": 2700000, "top_investors": ["a16z", "Bain Capital Ventures"], "thesis_tags": ["AI-native", "regulatory compliance", "finance", "automation"], "business_model": "SaaS", "target_customer": "Banks and asset managers", "source": "StrictlyVC", "fit_reasoning": "Perfect mandate match — AI-native, regulatory compliance, finance vertical, seed stage.", "recommended_next_step": "Immediate outreach. Top conviction opportunity."},
    {"name": "Kira Systems", "one_liner": "Machine learning contract review and analysis platform for legal professionals", "sector": "Legal Tech", "funding_stage": "acquired", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 0, "top_investors": ["Litera"], "thesis_tags": ["AI", "legal", "contract review", "B2B"], "business_model": "Enterprise SaaS", "target_customer": "Law firms and corporate legal", "source": "Crunchbase", "fit_reasoning": "Relevant comparable — acquired by Litera. Good competitive signal for legal AI thesis.", "recommended_next_step": "Use as comparable for investment memos."},
    {"name": "SigmaRed", "one_liner": "AI-powered threat intelligence and cybersecurity compliance for regulated industries", "sector": "Cybersecurity", "funding_stage": "seed", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 4200000, "top_investors": ["Crosslink Capital"], "thesis_tags": ["AI", "cybersecurity", "compliance", "regulated vertical"], "business_model": "SaaS", "target_customer": "Financial institutions and healthcare", "source": "VentureBeat", "fit_reasoning": "Regulated verticals (finance, health), compliance automation, seed stage.", "recommended_next_step": "Request intro call. Adjacent to core mandate."},
    {"name": "Findem", "one_liner": "AI talent intelligence platform for recruiting at financial services firms", "sector": "HR Tech", "funding_stage": "Series B", "ai_score": 4, "fit_score": 2, "funding_amount_usd": 33000000, "top_investors": ["Canapi Ventures"], "thesis_tags": ["AI", "HR tech", "recruiting", "financial services"], "business_model": "SaaS", "target_customer": "Financial services talent teams", "source": "TechCrunch", "fit_reasoning": "Financial services adjacent but HR/recruiting is outside knowledge work automation mandate.", "recommended_next_step": "Pass."},
    {"name": "Casetext", "one_liner": "AI legal research assistant using GPT-4 for case law and brief drafting", "sector": "Legal Tech", "funding_stage": "acquired", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 0, "top_investors": ["Thomson Reuters"], "thesis_tags": ["AI", "legal research", "B2B", "generative AI"], "business_model": "SaaS", "target_customer": "Litigators and researchers", "source": "Crunchbase", "fit_reasoning": "Acquired by Thomson Reuters — strong proof point for legal AI thesis.", "recommended_next_step": "Use as exit comparable. Validates the category."},
    {"name": "Vigil AI", "one_liner": "AI AML and fraud detection platform for crypto exchanges and neobanks", "sector": "FinTech", "funding_stage": "seed", "ai_score": 4, "fit_score": 3, "funding_amount_usd": 2100000, "top_investors": ["Hummingbird Ventures"], "thesis_tags": ["AI", "AML", "compliance", "fintech"], "business_model": "SaaS", "target_customer": "Crypto exchanges and neobanks", "source": "TechCrunch", "fit_reasoning": "Finance compliance but crypto vertical is in the excluded sectors list.", "recommended_next_step": "Pass — crypto exposure conflicts with exclusion list."},
    {"name": "Wolters Kluwer CCH", "one_liner": "Tax and accounting software platform with AI workflow automation", "sector": "FinTech", "funding_stage": "public", "ai_score": 3, "fit_score": 2, "funding_amount_usd": 0, "top_investors": ["Public markets"], "thesis_tags": ["tax", "accounting", "software", "enterprise"], "business_model": "Enterprise SaaS", "target_customer": "Accounting firms", "source": "Crunchbase", "fit_reasoning": "Public company, legacy software. Not relevant for early-stage mandate.", "recommended_next_step": "Pass — public incumbent."},
    {"name": "Spot AI", "one_liner": "AI video intelligence platform turning security cameras into business analytics", "sector": "Enterprise AI", "funding_stage": "Series B", "ai_score": 4, "fit_score": 2, "funding_amount_usd": 40000000, "top_investors": ["Scale Venture Partners"], "thesis_tags": ["AI", "video intelligence", "enterprise", "analytics"], "business_model": "SaaS", "target_customer": "Retail and logistics companies", "source": "TechCrunch", "fit_reasoning": "AI-native but not knowledge work or regulated vertical.", "recommended_next_step": "Pass."},
    {"name": "Primer AI", "one_liner": "AI platform for automating intelligence analysis and report generation for government", "sector": "GovTech", "funding_stage": "Series C", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 110000000, "top_investors": ["Addition", "Lux Capital"], "thesis_tags": ["AI-native", "intelligence analysis", "government", "automation"], "business_model": "Enterprise SaaS", "target_customer": "Government intelligence agencies", "source": "TechCrunch", "fit_reasoning": "AI-native knowledge work automation but defense/government is outside mandate. Too late stage.", "recommended_next_step": "Pass — sector exclusion."},
    {"name": "Anthropic Claude for Enterprise", "one_liner": "Enterprise AI assistant with extended context for complex knowledge work", "sector": "AI Infrastructure", "funding_stage": "Series D", "ai_score": 5, "fit_score": 2, "funding_amount_usd": 7300000000, "top_investors": ["Google", "Spark Capital"], "thesis_tags": ["AI", "enterprise", "foundation model", "infrastructure"], "business_model": "API + SaaS", "target_customer": "Enterprises", "source": "TechCrunch", "fit_reasoning": "Not investable — foundation model layer, not application layer.", "recommended_next_step": "Pass — infrastructure layer."},
    {"name": "Brightflag", "one_liner": "AI legal spend management and outside counsel analytics platform", "sector": "Legal Tech", "funding_stage": "Series B", "ai_score": 3, "fit_score": 4, "funding_amount_usd": 28000000, "top_investors": ["Elephant VC", "Molten Ventures"], "thesis_tags": ["AI", "legal ops", "spend management", "B2B SaaS"], "business_model": "SaaS", "target_customer": "In-house legal ops teams", "source": "StrictlyVC", "fit_reasoning": "Legal vertical, B2B SaaS, workflow automation. Late stage for fund.", "recommended_next_step": "Monitor."},
    {"name": "Aidoc", "one_liner": "AI radiology platform that triages and analyzes medical imaging 24/7", "sector": "HealthTech", "funding_stage": "Series D", "ai_score": 5, "fit_score": 3, "funding_amount_usd": 110000000, "top_investors": ["TLV Partners", "General Electric"], "thesis_tags": ["AI", "radiology", "healthcare", "diagnostics"], "business_model": "SaaS", "target_customer": "Hospital radiology departments", "source": "VentureBeat", "fit_reasoning": "Healthcare AI but imaging/diagnostics is outside knowledge work automation focus. Too late.", "recommended_next_step": "Pass."},
    {"name": "Carefull", "one_liner": "AI financial safety platform protecting older adults from fraud and mistakes", "sector": "FinTech", "funding_stage": "Series A", "ai_score": 3, "fit_score": 3, "funding_amount_usd": 13000000, "top_investors": ["Drive Capital"], "thesis_tags": ["AI", "finance", "fraud protection", "consumer"], "business_model": "B2B2C SaaS", "target_customer": "Financial advisors and banks", "source": "TechCrunch", "fit_reasoning": "Finance vertical but consumer-oriented, not knowledge worker automation.", "recommended_next_step": "Pass on thesis alignment."},
    {"name": "Synthetix", "one_liner": "AI customer support automation platform for regulated industries", "sector": "Enterprise AI", "funding_stage": "seed", "ai_score": 4, "fit_score": 4, "funding_amount_usd": 3100000, "top_investors": ["SaaStr Fund"], "thesis_tags": ["AI-native", "customer support", "regulated", "automation"], "business_model": "SaaS", "target_customer": "Banks, insurers, healthcare companies", "source": "ProductHunt", "fit_reasoning": "Regulated verticals focus, AI automating support workflows, seed stage.", "recommended_next_step": "Schedule intro call."},
    {"name": "Finix", "one_liner": "Payments infrastructure platform enabling companies to become payment facilitators", "sector": "FinTech", "funding_stage": "Series C", "ai_score": 2, "fit_score": 2, "funding_amount_usd": 100000000, "top_investors": ["Sequoia", "American Express"], "thesis_tags": ["fintech", "payments", "infrastructure", "B2B"], "business_model": "Transaction fee", "target_customer": "SaaS companies", "source": "TechCrunch", "fit_reasoning": "Not AI-native. Payments infrastructure outside knowledge work mandate.", "recommended_next_step": "Pass."},
]

async def seed():
    async with AsyncSessionLocal() as db:
        # Seed firm profile
        result = await db.execute(select(FirmProfile).where(FirmProfile.is_active == True))
        existing_profile = result.scalar_one_or_none()
        if not existing_profile:
            profile = FirmProfile(**FIRM_PROFILE)
            db.add(profile)
            await db.commit()
            print(f"Created firm profile: Failup Ventures")
        else:
            print(f"Firm profile already exists: {existing_profile.firm_name}")

        # Seed startups
        added = 0
        skipped = 0
        for data in STARTUPS:
            slug = slugify(data["name"])
            result = await db.execute(select(Startup).where(Startup.slug == slug))
            existing = result.scalar_one_or_none()
            if existing:
                skipped += 1
                continue
            startup = Startup(
                slug=slug,
                ai_summary=f"{data['one_liner']} — {data.get('fit_reasoning', '')}",
                **{k: v for k, v in data.items()}
            )
            db.add(startup)
            added += 1

        await db.commit()
        print(f"Seeded {added} startups, skipped {skipped} existing.")
        print(f"Total in database: {added + skipped}")

if __name__ == "__main__":
    asyncio.run(seed())
